name = "{{project-name}}"
version = "0.1.0"
authors = ["Your Name <your@email.com>"]
description = "A sample WASM plugin for Helix."
entrypoint = "{{project-name}}.wasm"

[activation]
on_command = ["{{project-name}}:*"]
